branches:
  only:
    - master
language: node_js
node_js:
 - "iojs"
script: 
 - "npm install grunt-cli --global && grunt build"

# create a GitHub Personal Access Token (https://github.com/settings/applications)
# install the travis gem (sudo gem install travis)
# and run the command below (fill in your name, email, and token)
# $ travis encrypt 'GIT_NAME="Your Name" GIT_EMAIL=you@example.com GH_TOKEN=token'
# replace the value of secure with your generated value
env:
 - secure: TG4X32vWbrFg68u8eutsv7EyYKaqkMGh71Sqxfhd2o/oZmxoiECJJXtba921J9gaMfY2BmhOpPq8R1tNjdEDSQ6IGaokgdy8biu8/xEYJRRnj35JnqtlRp/wXQI6IwgRArGv4uSTPTzVfUgRfRxVzpF3Vp2QxZdMR+DBfbP3cM4=
